# Bot Information
[info]
name = "كاغويا البوت"
version = "البوت هو حاليا في أصدار : $1"
author = "حسين يعقوبي"
title_process = "كاغويا البوت - $1:$2:$3"

# Index
[index]
host = "الاستماع على الميناء : $1"
invalid_credentials = "يرجى الذهاب إلى setup/credentials.json ملف واملأ fbstate!"
exists_credentials = "تم ايجاد credentials.json file -> جاري المضي قدما في تسجيل الدخول!..."
login_success = "تم الدخول بنجاح !"
login_error = "فشل الدخول !"
listen = "الاستماع حاليا للأحداث الجديدة !"
update = "البوت حاليا لديه إصدار جديد $1 -> $2! المرجو تحديثه على آخر إصدار : https://github.com/ttkienn/kaguya-project"
refresh_mqtt = "Refreshing MQTT in progress!"
refresh_mqtt_success = "MQTT refresh successful!"

# Database
[database]
type = "You have chosen the database type as: $1"
connection_success = "Connected to the database successfully!"
connection_failed = "Unable to connect to the database!"
create_user = "Successfully created data for the user: $1"
create_thread = "Successfully created data for the group: $1"

# Handler
[handler]
command_load = " ✅ |تم تحميل الأمر بنجاح : $1"
command_load_error = " ❌ |غير قادر على تحميل الأمر : $1 يتعلق ذالك بالخطأ : $2"
event_load = " ✅ | تم تحميل بنجاح : $1 من الأوامر"
event_load_error = " ❌ | فشل تحميل الإيفنتز : $1 يتعلق الأمر بالخطأ : $2"
command_noPermission = " ⚠️ | ليس لديك الصلاحية لإستخدام هذا الأمر ❗"
command_cooldowns = " ⏱️ | أنت تحتاح تنتظر $1 ثانية لتستخدمه مجددا !"
command_aliases_exists = " ⚠️ | ميزة الألقاب $1 هي بالفعل مستخدمة بالنسبة للأمر $2 ، لذالك لا يمكن تحميل الأمر $3!"
error = " ❌ |حدث خطأ : $1"
thread_ban = " ❌ | مجموعتكم تم حظرها من إستخدام كاغويا البوت والسبب : $1"
user_ban = "❌ | تم حظرك من إستخدام كاغويا البوت مع السبب : $1"
command_not_found = "هاذا الامر غير موجود 🙍‍♀️ 
اكتب اوامر لارأية الاوامر 💁‍♀️✓"

# plugins -> example plugins help.js
[plugins]
